### ISSUE TITLE
redirect to usage page is URL is absent

### ISSUE THREAD

**Issue by zeke** [hemanth/cors-now#1]
:wave:

For users who visit https://cors.now.sh in the browser, it would be nice to redirect to this repo so they can learn how to property use it. Or the current error message could be updated to include example usage. Currently it's:

> Error: only absolute urls are supported

**Comment by hemanth** [comment]
Yup, the error was just obvious for me, so thought it would be for all, but that was a bad move.

How about displaying the contents of the readme on the landing page rather than redirecting?

**Comment by hemanth** [comment]
[this](https://cors.now.sh) looks better?

**Comment by zeke** [comment]
👍
