### ISSUE TITLE
Site is not configured issue

### ISSUE THREAD

**Issue by iyunusp** [hemanth/cors-now#6]
when i visit on some old web i got "Site is not configured for host cors.now.sh !" output, what it means? and is there any workaround to fix this? thanks.

**Comment by TooTallNate** [comment]
Hi. What is the URL that produces the problem? Thanks.

**Comment by iyunusp** [comment]
well, it's some adult website http://nopixeljaps.com/ . if this link violates some github rule, i'll edit and remove it ASAP. Thanks.
