### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by markronquillo** [hemanth/cors-now#7]
Good day,

I think the site is down as of feb 24, 2018.

<img width="1253" alt="screen shot 2018-02-24 at 9 49 49 am" src="https://user-images.githubusercontent.com/1182515/36624286-214a795c-1948-11e8-95eb-114f5de61ff7.png">

**Comment by infiniteluke** [comment]
I experienced the same issue. It appears it just needs to be redeployed. I forked the repo, installed, and ran now and it works fine for me. You can use 

https://cors-new.now.sh

now if you'd like

**Comment by markronquillo** [comment]
Thanks luke.
