### ISSUE TITLE
How to make it work with Chromecast

### ISSUE THREAD

**Issue by rangav** [hemanth/cors-now#8]
Hi,

I am trying to cast youtube live streams in chromecast, i am still getting cors error using crossorigin.me proxy.

Do any know how to make it work with chromecast?

Example live stream
https://www.youtube.com/watch?v=XOacA3RYrXk

Thanks

**Comment by rangav** [comment]
Thanks its working now

**Comment by hemanth** [comment]
Nice, it would helpful if you can update how it was resolved, thanks.
